-- 0047_programs_ops_rls.sql — RLS for Programs ops tables.
-- Expenses/visits/reports/funding follow the standard org-scoped pattern.
-- CASES are special: only case workers (admins + area managers) and the
-- assigned worker may read them; restricted fields are additionally masked in
-- the API layer for viewers without case clearance. The access log is
-- INSERT-ONLY — rows can never be updated or deleted by app roles, so the
-- audit trail of who saw a case is tamper-evident. Cases never join into
-- donor reports or any general reporting endpoint.

-- Helper: the caller's auth uid as text (assigned_worker_id is text).
create or replace function auth_user_id() returns text as $$
  select auth.uid()::text;
$$ language sql stable;

alter table project_expenses    enable row level security;
alter table field_visits        enable row level security;
alter table donor_reports       enable row level security;
alter table cases               enable row level security;
alter table case_access_log     enable row level security;
alter table funding_sources     enable row level security;
alter table funding_repayments  enable row level security;

-- ── Project expenses: staff read; admins/accountants/program roles write ────
create policy "project_expenses_read" on project_expenses
  for select to authenticated
  using (org_id = auth_org_id());

create policy "project_expenses_manage" on project_expenses
  for all to authenticated
  using (
    org_id = auth_org_id()
    and auth_user_role() in ('super_admin','org_admin','area_manager','branch_manager','accountant','account_officer')
  )
  with check (
    org_id = auth_org_id()
    and auth_user_role() in ('super_admin','org_admin','area_manager','branch_manager','accountant','account_officer')
  );

-- ── Field visits: staff read; field staff write ──────────────────────────────
create policy "field_visits_read" on field_visits
  for select to authenticated
  using (org_id = auth_org_id());

create policy "field_visits_write" on field_visits
  for all to authenticated
  using (
    org_id = auth_org_id()
    and auth_user_role() in ('super_admin','org_admin','area_manager','branch_manager','accountant','account_officer')
  )
  with check (
    org_id = auth_org_id()
    and auth_user_role() in ('super_admin','org_admin','area_manager','branch_manager','accountant','account_officer')
  );

-- ── Donor reports: read by all staff; generated by admins/program roles ─────
create policy "donor_reports_read" on donor_reports
  for select to authenticated
  using (org_id = auth_org_id());

create policy "donor_reports_manage" on donor_reports
  for all to authenticated
  using (
    org_id = auth_org_id()
    and auth_user_role() in ('super_admin','org_admin','area_manager','branch_manager','accountant')
  )
  with check (
    org_id = auth_org_id()
    and auth_user_role() in ('super_admin','org_admin','area_manager','branch_manager','accountant')
  );

-- ── CASES: strict — no general-staff select. ────────────────────────────────
-- Case workers (super_admin/org_admin/area_manager) and the assigned worker
-- only. account_officer and branch_manager have NO read access here.
create policy "cases_case_worker_read" on cases
  for select to authenticated
  using (
    org_id = auth_org_id()
    and (
      auth_user_role() in ('super_admin','org_admin','area_manager')
      or assigned_worker_id = auth_user_id()
    )
  );

create policy "cases_case_worker_write" on cases
  for all to authenticated
  using (
    org_id = auth_org_id()
    and (
      auth_user_role() in ('super_admin','org_admin','area_manager')
      or assigned_worker_id = auth_user_id()
    )
  )
  with check (
    org_id = auth_org_id()
    and (
      auth_user_role() in ('super_admin','org_admin','area_manager')
      or assigned_worker_id = auth_user_id()
    )
  );

-- ── Case access log: INSERT-ONLY audit trail ─────────────────────────────────
-- Case workers may append entries for cases they can see; nobody may update
-- or delete. Non-case-workers cannot even insert, so the log is complete.
create policy "case_access_log_insert" on case_access_log
  for insert to authenticated
  with check (
    org_id = auth_org_id()
    and user_id = auth_user_id()
    and exists (
      select 1 from cases c
      where c.id = case_id
        and c.org_id = auth_org_id()
        and (
          auth_user_role() in ('super_admin','org_admin','area_manager')
          or c.assigned_worker_id = auth_user_id()
        )
    )
  );

-- No select/update/delete policies on case_access_log for app roles: only the
-- service role (used by the case endpoints) may read it back. This keeps the
-- audit trail tamper-evident even for case workers.

-- ── Funding sources & repayments: finance-tier manage, staff read ───────────
create policy "funding_sources_read" on funding_sources
  for select to authenticated
  using (org_id = auth_org_id());

create policy "funding_sources_manage" on funding_sources
  for all to authenticated
  using (
    org_id = auth_org_id()
    and auth_user_role() in ('super_admin','org_admin','area_manager','branch_manager','accountant')
  )
  with check (
    org_id = auth_org_id()
    and auth_user_role() in ('super_admin','org_admin','area_manager','branch_manager','accountant')
  );

create policy "funding_repayments_read" on funding_repayments
  for select to authenticated
  using (org_id = auth_org_id());

create policy "funding_repayments_manage" on funding_repayments
  for all to authenticated
  using (
    org_id = auth_org_id()
    and auth_user_role() in ('super_admin','org_admin','area_manager','branch_manager','accountant')
  )
  with check (
    org_id = auth_org_id()
    and auth_user_role() in ('super_admin','org_admin','area_manager','branch_manager','accountant')
  );
